student_management_system/student_management_app/urls.py
from django.urls import path
from student_management_app import views


urlpatterns = [
    path('', views.login_page, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('register-as', views.register_as_page, name="register"),
    path('register-admin', views.admin_register_page, name="register-admin"),
    path('register-secretary', views.secretary_register_page, name="register-secretary"),
    path('register-student', views.student_register_page, name="register-student"),


    #Admin urls
    path('admin-dashboard', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-announcement', views.admin_announcement_view, name='admin-announcement'),
    path('admin-view-secretary', views.admin_view_secretary_view, name='admin-view-secretary'),
    path('admin-approve-secretary', views.admin_approve_secretary_view, name='admin-approve-secretary'),
    path('approve-secretary/<int:pk>', views.approve_secretary_view, name='approve-secretary'),
    path('reject-secretary/<int:pk>', views.reject_secretary_view, name='reject-secretary'),
    path('admin-add-secretary', views.admin_add_secretary_view, name='admin-add-secretary'),
    path('update-secretary/<int:pk>', views.admin_update_secretary_view, name='update-secretary'),
    path('delete-secretary/<int:pk>', views.admin_delete_secretary_view, name='delete-secretary'),

    path('admin-view-student', views.admin_view_student_view, name='admin-view-student'),
    path('admin-approve-student', views.admin_approve_student_view, name='admin-approve-student'),
    path('approve-student/<int:pk>', views.approve_student_view, name='approve-student'),
    path('reject-student/<int:pk>', views.reject_student_view, name='reject-student'),
    path('admin-add-student', views.admin_add_student_view, name='admin-add-student'),
    path('update-student/<int:pk>', views.admin_update_student_view, name='update-student'),
    path('delete-student/<int:pk>', views.admin_delete_student_view, name='delete-student'),

    # Secretary urls
    path('secretary-dashboard', views.secretary_dashboard_view, name='secretary-dashboard'),
    path('secretary-announcement', views.secretary_announcement_view, name='secretary-announcement'),

    #Student urls
    path('student-dashboard', views.student_dashboard_view, name='student-dashboard'),
]

student_management_system/student_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student_management_app.urls')),
]

student_management_system/student_management_app/models.py
from django.contrib.auth.models import User
from django.db import models


class AdminExtraInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone_number = models.CharField(max_length=40, null=True)

	def __str__(self):
		return str(self.user)


class SecretaryExtraInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	join_date = models.DateField(auto_now_add=True)
	phone_number = models.CharField(max_length=40, null=True)
	status = models.BooleanField(default=False)

	def __str__(self):
		return str(self.user)

	@property
	def get_id(self):
		return self.user.id

	@property
	def get_name(self):
		return self.user.first_name + " " + self.user.last_name

	@property
	def get_email(self):
		return self.user.email

	@property
	def get_username(self):
		return self.user.username


class StudentExtraInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	join_date = models.DateField(auto_now_add=True)
	phone_number = models.CharField(max_length=40, null=True)
	status = models.BooleanField(default=False)

	def __str__(self):
		return str(self.user)

	@property
	def get_id(self):
		return self.user.id

	@property
	def get_name(self):
		return self.user.first_name + " " + self.user.last_name

	@property
	def get_email(self):
		return self.user.email

	@property
	def get_username(self):
		return self.user.username



class Announcement(models.Model):
	date = models.DateField(auto_now=True)
	by = models.CharField(max_length=20, null=True, default='school')
	message = models.CharField(max_length=500)

student_management_system/templates/secretary/secretary-announcement.html
{% extends 'secretary/secretary-index.html' %}
{% load static %}


{% block content %}
    <h1 class="mt-4">Announcement</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/secretary-dashboard">Dashboard</a></li>
        <li class="breadcrumb-item active">Announcement</li>
    </ol>
    <div class="card mb-4">
      <div class="card-header">
        <i class="fa-solid fa-bullhorn"></i>
        Make an announcement
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          <div class="form-outline mb-4">
            <textarea type="text" name="message" maxlength="500" placeholder="Write Your Message Here" class="form-control" required="" id="id_message" rows="4"></textarea>
          </div>
          <div>
              <input type="hidden" name="by" value="school" maxlength="20" placeholder="Your Name" class="form-control" required="" id="id_by">
          </div>
          <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
        </form>
      </div>
    </div>
{% endblock content %}

student_management_system/templates/secretary/secretary-index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Admin Dashboard - Student Management System</title>
  <link href="{% static 'https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css' %}" rel="stylesheet" />
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
  <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-2 text-wrap fs-6" href="/secretary-dashboard">Student Management System</a>

    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
        class="fas fa-bars"></i></button>
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">

    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
          aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="/logout">Logout</a></li>
        </ul>
      </li>
    </ul>
  </nav>
  
  <div id="layoutSidenav">
    <div id="layoutSidenav_nav">
      <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
          <div class="nav">
            
            <div class="sb-sidenav-menu-heading">Core</div>
            
            <a class="nav-link" href="/secretary-dashboard">
              <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
              Dashboard
            </a>

            <a class="nav-link" href="/secretary-announcement">
              <div class="sb-nav-link-icon"><i class="fa-solid fa-bullhorn"></i></div>
              Announcement
            </a>

          </div>
        </div>

        <div class="sb-sidenav-footer">
          <div class="small">Logged in as:</div>
          {{request.user.first_name}} {{ request.user.last_name }}
        </div>
      </nav>
    </div>
    
    <div id="layoutSidenav_content">
      <main>
        <div class="container-fluid px-4">
            {% block content %}
                <h1 class="mt-4">Dashboard</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>

                <!-- Announcement Alerts -->
                <div class="card mb-4">
            <div class="card-header">
              <i class="fa-solid fa-bullhorn"></i>
              Announcements
            </div>
            <div class="card-body">
                {%for a in announcements%}
              <div class="alert alert-primary d-flex justify-content-between" role="alert">
                <!-- A simple primary alert—check it out! -->
                <div>
                  <strong>Posted on {{a.date}} </strong><br><b>By : {{a.by}}</b><br> {{a.message}}
                </div>
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
              </div>
                {%endfor%}
            </div>
          </div>
            {% endblock content %}
        </div>
      </main>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
  <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
  <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
</body>

</html>