student_management_system/student_management_app/urls.py
from django.urls import path
from student_management_app import views


urlpatterns = [
    path('', views.login_page, name="login"),
    path('logout', views.logout_user, name="logout"),
    path('register-as', views.register_as_page, name="register"),
    path('register-admin', views.admin_register_page, name="register-admin"),
    path('register-secretary', views.secretary_register_page, name="register-secretary"),
    path('register-student', views.student_register_page, name="register-student"),


    #Admin urls
    path('admin-dashboard', views.admin_dashboard_view, name='admin-dashboard'),
    path('admin-announcement', views.admin_announcement_view, name='admin-announcement'),
    path('admin-view-secretary', views.admin_view_secretary_view, name='admin-view-secretary'),
    path('admin-approve-secretary', views.admin_approve_secretary_view, name='admin-approve-secretary'),
    path('approve-secretary/<int:pk>', views.approve_secretary_view, name='approve-secretary'),
    path('reject-secretary/<int:pk>', views.reject_secretary_view, name='reject-secretary'),
    path('admin-add-secretary', views.admin_add_secretary_view, name='admin-add-secretary'),
    path('update-secretary/<int:pk>', views.admin_update_secretary_view, name='update-secretary'),
    path('delete-secretary/<int:pk>', views.admin_delete_secretary_view, name='delete-secretary'),

    path('admin-view-student', views.admin_view_student_view, name='admin-view-student'),
    path('admin-approve-student', views.admin_approve_student_view, name='admin-approve-student'),
    path('approve-student/<int:pk>', views.approve_student_view, name='approve-student'),
    path('reject-student/<int:pk>', views.reject_student_view, name='reject-student'),
    path('admin-add-student', views.admin_add_student_view, name='admin-add-student'),
    path('update-student/<int:pk>', views.admin_update_student_view, name='update-student'),
    path('delete-student/<int:pk>', views.admin_delete_student_view, name='delete-student'),

    # Secretary urls
    path('secretary-dashboard', views.secretary_dashboard_view, name='secretary-dashboard'),
    path('secretary-announcement', views.secretary_announcement_view, name='secretary-announcement'),

    #Student urls
    path('student-dashboard', views.student_dashboard_view, name='student-dashboard'),
]

student_management_system/student_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student_management_app.urls')),
]

student_management_system/student_management_app/models.py
from django.contrib.auth.models import User
from django.db import models


class AdminExtraInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	phone_number = models.CharField(max_length=40, null=True)

	def __str__(self):
		return str(self.user)


class SecretaryExtraInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	join_date = models.DateField(auto_now_add=True)
	phone_number = models.CharField(max_length=40, null=True)
	status = models.BooleanField(default=False)

	def __str__(self):
		return str(self.user)

	@property
	def get_id(self):
		return self.user.id

	@property
	def get_name(self):
		return self.user.first_name + " " + self.user.last_name

	@property
	def get_email(self):
		return self.user.email

	@property
	def get_username(self):
		return self.user.username


class StudentExtraInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	join_date = models.DateField(auto_now_add=True)
	phone_number = models.CharField(max_length=40, null=True)
	status = models.BooleanField(default=False)

	def __str__(self):
		return str(self.user)

	@property
	def get_id(self):
		return self.user.id

	@property
	def get_name(self):
		return self.user.first_name + " " + self.user.last_name

	@property
	def get_email(self):
		return self.user.email

	@property
	def get_username(self):
		return self.user.username



class Announcement(models.Model):
	date = models.DateField(auto_now=True)
	by = models.CharField(max_length=20, null=True, default='school')
	message = models.CharField(max_length=500)

student_management_system/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
</head>
<body>
    <h1>Hello</h1>
</body>
</html>

student_management_system/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - Student Management System</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/show-password-toggle.min.css' %}" rel="stylesheet" />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body class="bg-primary">
    <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
        <main>
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-5">
                <div class="my-4 text-center h2">
                  <a href="/" class="link-dark text-decoration-none pe-auto">Student Management System</a>
                </div>
                <div class="card shadow border-1 rounded-lg mt-3">
                  <div class="">
                    <h3 class="text-center font-weight-light my-4">Login</h3>
                  </div>
                  <div class="card-body py-1">
                    <form method="POST">
                        {% csrf_token %}
                      <div class="form-floating mb-2">
{#                        <input#}
{#                          class="form-control"#}
{#                          id="inputEmail"#}
{#                          type="email"#}
{#                          placeholder="name@example.com"#}
{#                        />#}
                          <input name="username" type="text" class="form-control" id="inputUsername" placeholder="Username">
                        <label for="inputUsername">Usermame</label>
                      </div>

                      <div class="form-floating mb-3">
                        <input name="password" type="password" id="inputPassword" class="form-control rounded" placeholder="Password" required>
                        <label for="inputPassword">Password</label>
                        <button id="toggle-password" type="button" class="d-none"
                            aria-label="Show password as plain text. Warning: this will display your password on the screen.">
                        </button>
                      </div>

{#                      <div class="form-floating mb-3">#}
{#                          <input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password">#}
{#                        <label for="inputPassword">Password</label>#}
{#                      </div>#}

                      <div class="d-flex align-items-center mt-2 mb-0">
                        <button class="form-control btn btn-primary rounded submit px-3" type="submit">Login</button>
                      </div>
                    </form>
                  </div>
                  <div class=" text-center py-3">
                    {% for message in messages %}
                        <p id="messages">{{ message }}</p>
{#                    <p id="messages">Account created</p>  #}
                    {% endfor %}
                    <div>
                      <a href="/forgot-password">Forgot Password?</a>
                    </div>
                    <div>
                      <a href="/register-as">Need an account? Sign up!</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>

      <!-- <div id="layoutAuthentication_footer">
        <footer class="py-4 bg-light mt-auto">
          <div class="container-fluid px-4">
            <div
              class="d-flex align-items-center justify-content-between small"
            >
              <div class="text-muted">Copyright &copy; Your Website 2022</div>
              <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
              </div>
            </div>
          </div>
        </footer>
      </div> -->

    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/show-password-toggle.min.js' %}"></script>
  </body>
</html>

student_management_system/templates/register-admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Admin Register</title>
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-primary">
  <div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
      <main>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-7">
              <div class="my-4 text-center h2">
                <a href="/" class="link-dark text-decoration-none pe-auto">Student Management System</a>
              </div>
              <div class="card shadow border-1 rounded-lg mt-3">
                <div>
                  <h3 class="text-center font-weight-light my-4">Create Admin Account</h3>
                </div>
                <div class="card-body py-1">
                  <form method="POST">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_first_name" type="text" name="first_name" maxlength="150" placeholder="Enter your first name" />
                          <label for="id_first_name">First name</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating">
                          <input class="form-control" id="id_last_name" type="text" name="last_name" maxlength="150" placeholder="Enter your last name" />
                          <label for="inputLastName">Last name</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_username" type="text" name="username" maxlength="150" required="" placeholder="Enter your Username" />
                          <label for="id_username">Username</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating">
                          <input class="form-control" id="id_email" type="email" name="email" maxlength="254" placeholder="Enter your Email Address" />
                          <label for="id_email">Email Address</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_password1" type="password" name="password1" autocomplete="new-password" required="" placeholder="Create a password" />
                          <label for="id_password1">Password</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_password2" type="password" name="password2" autocomplete="new-password" required="" placeholder="Confirm password" />
                          <label for="id_password2">Confirm Password</label>
                        </div>
                      </div>
                    </div>
                    <div class="form-floating mb-3">
                      <input class="form-control" id="id_phone_number" type="text" name="phone_number" maxlength="40" required="" placeholder="Enter your Phone Number" />
                      <label for="id_phone_number">Phone Number</label>
                    </div>
                    <div class="mt-4 mb-0">
                      <div class="d-grid">
                          <input class="btn btn-primary btn-block" type="submit" name="Create User" value="Create Account">
                      </div>
                    </div>
                  </form>
                </div>

                <div class="text-center py-3">
                  {% for message in messages %}
                    <p id="messages">{{ message }}</p>
{#                    <p id="messages">Account created</p>  #}
                  {% endfor %}
                  <div><a href="/">Have an account? Go to login</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    crossorigin="anonymous"></script>
  <script src="js/scripts.js"></script>
</body>

</html>

student_management_system/templates/register-as.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Register as - Student Management System</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body class="bg-primary">
    <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
        <main>
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-5">
                <div class="my-4 text-center h2">
                  <a href="/" class="link-dark text-decoration-none pe-auto">Student Management System</a>
                </div>
                <div class="text-center py-3 m-10">
                  <h2>Register As</h2>
                </div>

                <!-- Added for register as selection -->
                <div class="select-containers">
                  <!-- <div class="container student"></div> -->
                  <a href="/register-student" class="container student">
                    <img src="{% static './assets/img/avatar-student.png' %}" alt="">
                    <p>Student</p>
                  </a>
                  <a href="/register-secretary" class="container secretary">
                    <img src="{% static './assets/img/avatar-secretary.png' %}" alt="">
                    <p>Secretary</p>
                  </a>  
                </div>
              
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>

</html>

student_management_system/templates/register-secretary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Secretary Register</title>
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="bg-primary">
  <div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
      <main>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-7">
              <div class="my-4 text-center h2">
                <a href="/" class="link-dark text-decoration-none pe-auto">Student Management System</a>
              </div>
              <div class="card shadow border-1 rounded-lg mt-3">
                <div>
                  <h3 class="text-center font-weight-light my-4">Create Secretary Account</h3>
                </div>
                <div class="card-body py-1">
                  <form method="POST">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_first_name" type="text" name="first_name" maxlength="150" placeholder="Enter your first name" />
                          <label for="id_first_name">First name</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating">
                          <input class="form-control" id="id_last_name" type="text" name="last_name" maxlength="150" placeholder="Enter your last name" />
                          <label for="inputLastName">Last name</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_username" type="text" name="username" maxlength="150" required="" placeholder="Enter your Username" />
                          <label for="id_username">Username</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating">
                          <input class="form-control" id="id_email" type="email" name="email" maxlength="254" placeholder="Enter your Email Address" />
                          <label for="id_email">Email Address</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_password1" type="password" name="password1" autocomplete="new-password" required="" placeholder="Create a password" />
                          <label for="id_password1">Password</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_password2" type="password" name="password2" autocomplete="new-password" required="" placeholder="Confirm password" />
                          <label for="id_password2">Confirm Password</label>
                        </div>
                      </div>
                    </div>
                    <div class="form-floating mb-3">
                      <input class="form-control" id="id_phone_number" type="text" name="phone_number" maxlength="40" required="" placeholder="Enter your Phone Number" />
                      <label for="id_phone_number">Phone Number</label>
                    </div>
                    <div class="mt-4 mb-0">
                      <div class="d-grid">
                          <input class="btn btn-primary btn-block" type="submit" name="Create User" value="Create Account">
                      </div>
                    </div>
                  </form>
                </div>

                <div class="text-center py-3">
                  {% for message in messages %}
                    <p id="messages">{{ message }}</p>
{#                    <p id="messages">Account created</p>  #}
                  {% endfor %}
                  <div><a href="/">Have an account? Go to login</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    crossorigin="anonymous"></script>
  <script src="js/scripts.js"></script>
</body>

</html>

student_management_system/templates/register-student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Student Register</title>
  <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  <link href="{% static 'css/show-password-toggle.min.css' %}" rel="stylesheet" />
</head>

<body class="bg-primary">
  <div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
      <main>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-7">
              <div class="my-4 text-center h2">
                <a href="/" class="link-dark text-decoration-none pe-auto">Student Management System</a>
              </div>
              <div class="card shadow border-1 rounded-lg mt-3">
                <div>
                  <h3 class="text-center font-weight-light my-4">Create Student Account</h3>
                </div>
                <div class="card-body py-1">
                  <form method="POST">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_first_name" type="text" name="first_name" maxlength="150" placeholder="Enter your first name" />
                          <label for="id_first_name">First name</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating">
                          <input class="form-control" id="id_last_name" type="text" name="last_name" maxlength="150" placeholder="Enter your last name" />
                          <label for="inputLastName">Last name</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_username" type="text" name="username" maxlength="150" required="" placeholder="Enter your Username" />
                          <label for="id_username">Username</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating">
                          <input class="form-control" id="id_email" type="email" name="email" maxlength="254" placeholder="Enter your Email Address" />
                          <label for="id_email">Email Address</label>
                        </div>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_password1" type="password" name="password1" autocomplete="new-password" required="" placeholder="Create a password" />
                          <label for="id_password1">Password</label>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-floating mb-3 mb-md-0">
                          <input class="form-control" id="id_password2" type="password" name="password2" autocomplete="new-password" required="" placeholder="Confirm password" />
                          <label for="id_password2">Confirm Password</label>
                        </div>
                      </div>
                    </div>
                    <div class="form-floating mb-3">
                      <input class="form-control" id="id_phone_number" type="text" name="phone_number" maxlength="40" required="" placeholder="Enter your Phone Number" />
                      <label for="id_phone_number">Phone Number</label>
                    </div>
                    <div class="mt-4 mb-0">
                      <div class="d-grid">
                          <input class="btn btn-primary btn-block" type="submit" name="Create User" value="Create Account">
                      </div>
                    </div>
                  </form>
                </div>

                <div class="text-center py-3">
                  {% for message in messages %}
                    <p id="messages">{{ message }}</p>
{#                    <p id="messages">Account created</p>  #}
                  {% endfor %}
                  <div><a href="/">Have an account? Go to login</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    crossorigin="anonymous"></script>
  <script src="js/scripts.js"></script>
</body>

</html>

student_management_system/templates/secretary-wait-approval.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Approve - Student Management System</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body class="bg-primary">
    <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
        <main>
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-7">
                <div class="my-4 text-center h2">
                  <a href="/logout" class="link-dark text-decoration-none pe-auto">Student Management System</a>
                </div>

                <div class=" text-center style="margin-top: 0px; margin-bottom: 0px;">
                  <h1 class="display-6">Hello {{request.user.first_name}},</h1>
                  <p class="lead">Your Account has not been approved yet!<br>Our Administrative Team will be checking it soon.
                    <br>You'll get to access the system after the confirmation.</p>
                  <hr class="my-4">
                  <p>Please check later</p>
                  <p class="lead">
                    <a class="btn btn-danger btn-lg" href="/logout" role="button">Logout</a>
                  </p>
                </div>

              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

student_management_system/templates/student-wait-approval.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Approve - Student Management System</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <script
      src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body class="bg-primary">
    <div id="layoutAuthentication">
      <div id="layoutAuthentication_content">
        <main>
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <div class="my-4 text-center h2">
                  <a href="/logout" class="link-dark text-decoration-none pe-auto">Student Management System</a>
                </div>

                <div class=" text-center style="margin-top: 0px; margin-bottom: 0px;">
                  <h1 class="display-6">Hello {{request.user.first_name}},</h1>
                  <p class="lead">Your Account has not been approved yet!<br>Our Administrative Team will be checking it soon. <br> And, soon your admission will be confirmed ! You'll get to access the system after the confirmation.</p>
                  <p class="lead">Thank you for signing up. We'll see you soon.</p>
                  <hr class="my-4">
                  <p>Please check later</p>
                  <p class="lead">
                    <a class="btn btn-danger btn-lg" href="/logout" role="button">Logout</a>
                  </p>
                </div>

              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

student_management_system/templates/user-logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>User {{ request.user }} Logged!</h1>
    <a href="/logout">logout</a>
</body>
</html>